### ISSUE TITLE
Completely borderless table

### ISSUE THREAD

**Issue by timster** [jmaczan/bulma-helpers#3]
First of all thanks for this project. It's been very helpful.

Since bulma applies the table borders to the individual cells, getting a completely borderless table is kind of tedius:

```html
<table class="table">
    <tr>
        <th class="is-borderless">Header 1</th>
        <th class="is-borderless">Header 2</th>
    </tr>
    <tr>
        <td class="is-borderless">Cell 1</td>
        <td class="is-borderless">Cell 2</td>
    </tr>
</table>
```

It would be nice to be able to apply it to just the table and have it cascade down:

```html
<table class="table is-borderless">
    <tr>
        <th>Header 1</th>
        <th>Header 2</th>
    </tr>
    <tr>
        <td>Cell 1</td>
        <td>Cell 2</td>
    </tr>
</table>
```

Basically, this:

```sass
.table.is-borderless
  td, 
  th
    border: 0
```

Is this a helper you would consider adding?

**Comment by jmaczan** [comment]
Hello Tim,

Sound like a plan :slightly_smiling_face: I'm gonna implement it in a days.

**Comment by jmaczan** [comment]
Done in version 0.3.2. [https://www.npmjs.com/package/bulma-helpers/v/0.3.2](https://www.npmjs.com/package/bulma-helpers/v/0.3.2)

**Comment by coderabsolute** [comment]
I don't see this functionality in the documentation. Not sure `is-borderless` is still implemented in the current version (0.9.2)?

**Comment by cabrace** [comment]
``` css
// can be achieved with
.table.is-borderless td, .table.is-borderless th {
 border: 0;
}
```
``` html
<!-- Applied to  table element class -->
<table class="table is-borderless">
...
</table>

**Comment by campZero** [comment]
It's now 0.9.4, and
`<table class="table is-borderless">` still doesn't work.

**Comment by MartinX3** [comment]
Yeah, but it isn't working without the css hack even with the helper.
But with the css hack we don't need the helper as well.
